apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-producer-persistent-volume
  labels:
    app: order-producer
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço order-producer"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/order-producer/logs
