name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Permissões para gerar o id-token

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore OrderProducerService.sln

      - name: Build
        run: dotnet build OrderProducerService.sln --configuration Release

      - name: Start API in Background
        env:
          ASPNETCORE_URLS: http://localhost:5010
        run: |
          cd OrderProducerService.Api/bin/Release/net9.0/
          dotnet OrderProducerService.Api.dll & disown
          sleep 5

      - name: Wait for API to Start
        run: |
          for i in {1..10}; do
            echo "Tentando acessar endpoint de health..."
            curl -v http://localhost:5010/order-producer/health || true
            if curl -f http://localhost:5010/order-producer/health > /dev/null 2>&1; then
              echo "API started successfully"
              exit 0
              fi
              echo "Waiting for API to start... Attempt $i of 10"
              sleep 3
            done
            echo "API failed to start"
            exit 1

      - name: Test API Health
        run: curl -f http://localhost:5010/order-producer/health || exit 1

      - name: Test API Metrics
        run: curl -f http://localhost:5010/order-producer/metrics || exit 1

      # - name: Run Unit Tests        
      #   run: dotnet test CriarContatos.Test/CriarContatos.Test.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Publish
        run: dotnet publish OrderProducerService.Api/OrderProducerService.Api.csproj --configuration Release --output OrderProducerService.Api/publish

      # --- Adicionando as etapas de Docker, ACR e AKS ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEFAULT_DIRECTORY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure CLI (Using Managed Identity)
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Verificar se o cluster Kubernetes está acessível
        run: |
          if kubectl cluster-info; then
            echo "Cluster Kubernetes está acessível"
          else
            echo "Falha ao acessar o cluster Kubernetes"
            exit 1
          fi

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order-producer:latest -f OrderProducerService.Api/Dockerfile .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-producer:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.AKS_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AKS_CLUSTER_NAME }}'

      - name: Injetar timestamp para forçar rollout do Deployment
        run: |
          timestamp=$(date +%s)
          sed -i "s/{{timestamp}}/$timestamp/" OrderProducerService.Api/k8s/k8s-deployment.yml

      - name: Update Kubernetes Resources
        run: |
          # Aplica ConfigMap (cria ou atualiza se necessário)
          kubectl apply -f OrderProducerService.Api/k8s/k8s-configmap.yml

          # Aplica Deployment (cria ou atualiza se necessário)
          kubectl apply -f OrderProducerService.Api/k8s/k8s-deployment.yml

          # Aplica PVC e PV (apenas cria ou atualiza, sem deletar)
          kubectl apply -f OrderProducerService.Api/k8s/k8s-persistent-volume.yml
          kubectl apply -f OrderProducerService.Api/k8s/k8s-persistent-volume-claim.yml

          # Aplica Service (cria ou atualiza se necessário)
          kubectl apply -f OrderProducerService.Api/k8s/k8s-service.yml

          # Aplica o Ingress (cria ou atualiza o roteamento externo)
          kubectl apply -f OrderProducerService.Api/k8s/k8s-ingress.yml

          # Espera o rollout do Deployment para garantir que a atualização foi bem-sucedida
          kubectl rollout status deployment/order-producer-deployment
      
      - name: Update AKS Deployment with new image
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            OrderProducerService.Api/k8s/k8s-deployment.yml
            OrderProducerService.Api/k8s/k8s-service.yml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/order-producer:latest
          # imagepullsecrets: |
          #   acr-order-producer

      - name: Cleanup
        if: always()
        run: |
          docker rm -f rabbitmq || true
          docker volume prune -f

          